### ISSUE TITLE
Error when click on Options/Preferences on https://viewer.ohif.org/

### ISSUE THREAD

**Issue by vn09** [OHIF/Viewers#1413] opened 2020-02-03 15:43 UTC
> **Before Creating an issue**
>
> - Are you running the latest version?
> - Are you reporting to the correct repository?
> - Did you search existing issues?

### Describe the Bug

The bug is shown in the following images.
<img width="1435" alt="Screen Shot 2020-02-03 at 10 39 08 PM" src="https://user-images.githubusercontent.com/22481592/73667017-3e46e280-46d6-11ea-98f6-50f8c0621481.png">
<img width="904" alt="Screen Shot 2020-02-03 at 10 39 51 PM" src="https://user-images.githubusercontent.com/22481592/73667020-3e46e280-46d6-11ea-852e-3e571ef7a263.png">

### What steps can we follow to reproduce the bug?

1. Access website https://viewer.ohif.org/
2. Click on Options/Preferences

```js
Please use code blocks to show formatted errors or code snippets
```

> :warning: Reports we cannot reproduce are at risk of being marked stale and
> closed. The more information you can provide, the more likely we are to look
> into and address your issue.

**Comment by dannyrb** [comment] 2020-02-05 15:18
@vn09, can you try:

- Open Chrome Inspector
- Navigate to `Storage` tab
- Expand `Local Storage`
- Select the only item
- Right click "State", Delete

This issue is likely caused by previously cached hotkeys schema no longer being valid in the current version. If we detect invalid schema, our app should be clearing the old and using the new; this is a bug, but the steps above verify it's existence.

**Comment by vn09** [comment] 2020-02-06 15:34
Hi @dannyrb,
It works now when I delete variable in Local Storage. Thanks.

**Comment by dannyrb** [comment] 2020-02-06 16:07
At a minimum, we should catch the error caused if their is a schema discrepancy and clear the old state, then use the new initial hotkeys state. Because the error may not be thrown until the state is applied, we may need to version the schema, and compare the version at time of restore

**Comment by sedghi** [comment] 2023-10-12 20:37
I don't think this happens in latest master. 

Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.

**Closed by sedghi** 2023-10-12 20:37 UTC
Labels: Bug: Verified :bug:
