### ISSUE TITLE
MPR doesn't work when I use JSON schema

### ISSUE THREAD

**Issue by starSinking** [OHIF/Viewers#3084] opened 2022-12-21 07:14 UTC
branch: v3-stable

### Describe the Bug

When I open the file in JSON mode and then use the MPR function, it doesn't work properly and an error is reported on the console (Cannot read properties of undefined (reading 'split'))

![image](https://user-images.githubusercontent.com/43055274/208842494-fded14b5-8916-4aba-99ff-45324aa600db.png)
![image](https://user-images.githubusercontent.com/43055274/208843634-40af5b2e-f9ce-4698-8670-9e1d0bf14a3f.png)

**Comment by shlomgad** [comment] 2023-01-07 15:45
This is also happening to me.
Looking at the code, it seems that MetadataProvider.js is expecting an imageId in the form of a wadors query (../studies/../series/..) which is not necessarily the case when images are loaded from a JSON manifest and this is causing this error.

**Comment by jbocce** [comment] 2023-01-12 19:51
@starSinking and @shlomgad thanks for posting. However, I was not able to reproduce this problem. Perhaps try pulling the latest v3-stable code and try again?
![image](https://user-images.githubusercontent.com/109477394/212166877-583af489-a84a-449d-a50e-95b6c678a47d.png)

**Comment by starSinking** [comment] 2023-01-13 01:52
@jbocce Thanks for answer. I pulled the latest code for v3-stable and found that the issue had been resolved.It may have been resolved in a single commit
![image](https://user-images.githubusercontent.com/43055274/212218023-e6d0d0d1-cfbb-4bf0-9312-23995c7630ba.png)
![image](https://user-images.githubusercontent.com/43055274/212218729-7d2cfc73-2f5f-492b-b73a-fa226fd535b5.png)

**Comment by jbocce** [comment] 2023-01-13 16:46
Likely fixed by 1d1b33224ad95a99e669e08ec1da809fb8880102.

**Closed by jbocce** 2023-01-13 16:46 UTC
Labels: Community: Report :bug:
