### ISSUE TITLE
showStackLoadingProgressBar in Standalone Viewer

### ISSUE THREAD

**Issue by richsmith123** [OHIF/Viewers#110] opened 2017-09-02 18:22 UTC
Hello,

showStackLoadingProgressBar does not show progress bar at the bottom of thumbnail when using Standalone viewer.

Many thanks!
Rick

**Comment by ayselafsar** [comment] 2017-10-07 16:11
Hi @richsmith123,

The fix for the issue is on master branch, commit: https://github.com/OHIF/Viewers/commit/b9b9a0f00dfc1dccf6fee905974538e15963c318

Could you please give it a try? Thanks.

**Comment by richsmith123** [comment] 2017-10-08 14:38
Many thanks sir!  I will try and get back to  you.

Warm regards,
Rick

**Comment by swederik** [comment] 2017-10-19 13:18
Closing since this should be fixed. Feel free to reopen it if it's not working.

**Closed** 2017-10-19 13:18 UTC
Labels: enhancement, standalone

**Comment by Boukenty** [comment] 2017-11-21 16:15
Hello,

I have same problem on last version with standalone viewer.
no progressbar in series thumbnail image.
