### ISSUE TITLE
[Bug] Error after creating default template mode

### ISSUE THREAD

**Issue by junxiant** [OHIF/Viewers#3876] opened 2024-01-04 21:40 UTC
### Describe the Bug

In the default "Template Mode" after following the create-mode commands,
![image](https://github.com/OHIF/Viewers/assets/25401067/4efeb40d-8462-43af-a310-4a44a26f8759)

It shows some primary toolbar error
![image](https://github.com/OHIF/Viewers/assets/25401067/ee683105-cddd-4db4-a0ad-b7c7f62699e1)

### Steps to Reproduce

Followed the steps at https://docs.ohif.org/development/getting-started
```
git clone https://github.com/OHIF/Viewers
cd Viewers
yarn config set workspaces-experimental true
yarn install
```

Then followed the steps at https://docs.ohif.org/development/ohif-cli
```
yarn run cli create-mode
```
```
yarn run cli link-mode ...../
```

Then yarn run dev to get the site at localhost:3000,
Tried to view the new mode and it gave the error.

### The current behavior

Error shows up.

### The expected behavior

The page should load without errors, like this one in the video:

https://docs.ohif.org/development/video-tutorials/#creating-and-linking-a-mode

### OS

Ubuntu

### Node version

20.10.0

### Browser

Chrome, Brave

**Comment by junxiant** [comment] 2024-01-04 22:13
Just an update this works fine with 

git clone -b 3.7.0 https://github.com/OHIF/Viewers.git

**Comment by Pooouf** [comment] 2024-03-07 14:04
git bisect says the issue was caused by [the commit dd6d9768](https://github.com/OHIF/Viewers/commit/dd6d9768bbca1d3cc472e8c1e6d85822500b96ef)

**Comment by Pooouf** [comment] 2024-03-07 14:47
According to git bisect, the first bad commit was dd6d9768bbca1d3cc472e8c1e6d85822500b96ef

**Comment by sedghi** [comment] 2024-03-15 14:33
I think this is fixed, can you try and we close this ?

**Comment by sedghi** [comment] 2024-05-04 17:06
This is fixed

**Closed by sedghi** 2024-05-04 17:06 UTC
Labels: Awaiting Response
