### ISSUE TITLE
Yarn run build stuck at 93%

### ISSUE THREAD

**Issue by KhyatiMehta3** [OHIF/Viewers#1639] opened 2020-04-15 05:49 UTC
Hello!
I'm trying to run a `yarn run build` on the viewer and it always continues until 93% and then gets stuck. It even hangs my system. My system has an 8GB RAM, so I'm guessing that shouldn't be an issue either. 
![image](https://user-images.githubusercontent.com/25249564/79302748-db11d180-7f0a-11ea-92a8-a00cccc6002b.png)

`yarn run dev` works just fine. 
Can anyone help me out in figuring what the issue might be?

**Comment by dannyrb** [comment] 2020-04-15 13:24
The minifier can take 10+ minutes. It's a little ridiculous. I'm almost positive it's an issue caused by pulling in the `cornerstone-wado-image-loader` codecs.

You can set a `QUICK_BUILD=true` environment flag to bypass minification. We do that on our CI to  decrease build times.

**Comment by KhyatiMehta3** [comment] 2020-04-16 07:54
Okay, thanks Danny, 
would this successfully build the entire project for static web pages to not have any issues?

**Comment by dannyrb** [comment] 2020-04-20 03:16
> would this successfully build the entire project for static web pages to not have any issues?

Yes, but the code would not be minified.

**Comment by dannyrb** [comment] 2020-04-20 03:17
I'm going to close this, as I think the heart of the issue has been solved. FWIW, more than happy to hear guidance around improving build times or review PRs that help make it happen.

**Closed by dannyrb** 2020-04-20 03:17 UTC
Labels: Awaiting Reproduction, Community: Report :bug:

**Comment by matthiasg** [comment] 2020-10-13 07:39
> The minifier can take 10+ minutes. It's a little ridiculous. I'm almost positive it's an issue caused by pulling in the `cornerstone-wado-image-loader` codecs.

Interestingly it took multiple hours on my 32GB,SSD,24 Core machine. Was quite confusing. Quick makes it ok, but I would love to see a simple esbuild setup without minification or even bundling (just using es6 modules) for very quick iterations
