### ISSUE TITLE
latest master cannot show web page properly

### ISSUE THREAD

**Issue by zhaoyu162** [OHIF/Viewers#974] opened 2019-09-29 08:43 UTC
> :hand: We are a small team with limited resources. Your question is much more
> likely to be answered if it is
> [a good question](https://stackoverflow.com/help/how-to-ask)

I fetched latest master version and then install it by 'yarn install' successfully.
The viewer is started successfully by yarn dev command without any error messages.
But, the brower navigates to http://localhost:3000, just displayed the black blank page without anything thing else.
At the same time, I open the chrome debugger and find an error catched on console at this line:
error: manager.getactions is not a function.
It seems that rasied from react-dnd-touch components.
Please help, thank you all!

Questions can often be answered by our documentation. Unable to find an answer
in our docs? We'll try to help. In the meantime, if you answer your own
question, please respond with the answer here so that others may benefit as
well. Better yet, open a PR to expand our docs ^\_^

**Comment by jwitos** [comment] 2019-09-29 14:47
Hey @zhaoyu162, a few questions:
1. Can you show your log from terminal after you call `yarn run dev`?
2. What device/system are you running?
3. What is your npm version?

**Comment by zhaoyu162** [comment] 2019-09-29 15:24
hello juitos,
Thank you !
npm version is 6.11.3,
OS is windows 10,
AND the log as below:
yarn run v1.17.3
$ lerna run dev:viewer --stream
lerna notice cli v3.16.4
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev:viewer"
@ohif/viewer: $ yarn run dev
@ohif/viewer: $ cross-env NODE_ENV=development webpack-dev-server --config .webpack/webpack.pwa.js --watch
@ohif/viewer: i ｢wds｣: Project is running at http://localhost:3000/
@ohif/viewer: i ｢wds｣: webpack output is served from /
@ohif/viewer: i ｢wds｣: Content not from webpack is served from D:\extension\YinHui\Viewers-master (1)\Viewers-master\platform\viewer
@ohif/viewer: i ｢wds｣: 404s will fallback to /index.html
@ohif/viewer: i ｢wdm｣: wait until bundle finished: /

**Comment by dannyrb** [comment] 2019-09-30 02:44
@zhaoyu162, I'm unable to reproduce. Do you get the same result when you visit this recent Deploy Preview?

- https://deploy-preview-973--ohif.netlify.com/pwa/

Are you using a clean copy of the OHIF Viewer? Have you tried clearing your `node_modules` folder and running `yarn install` again? Are you able to create a CodeSandbox that reproduces your issue?

Unfortunately, I'm not sure I'll be able to help much until we can pin down the steps and environment required to reproduce your issue.

**Comment by zhaoyu162** [comment] 2019-09-30 09:09
Thank you @dannyrb !
I was processing it by cleaning the node_modules and trying again later.
Could you tell me your NPM version and yarn version?

**Comment by jwitos** [comment] 2019-09-30 13:07
@zhaoyu162, do you get a `Reference Error __webpack_require__ is not defined` in your debugger when running Deploy Preview from a link above?
If yes, can you try turning off any Chrome extensions? In my case running adblocker also resulted in black blank page and err above.

**Comment by zhaoyu162** [comment] 2019-09-30 15:38
Hi @jwitos , in debugger I still get this error for your linke as my local page previousely:
t.getActions is not a function
    at new e (TouchBackend.js:240)
    at Mc (index.js:5)
    at Sc (viewerbaseDragDropContext.js:13)
    at Object.<anonymous> (OHIFStandaloneViewer.js:235)
    at a (bootstrap:68)
    at Module.<anonymous> (app.bundle.8eff2465da13d1c41817.js:3082)
    at a (bootstrap:68)
    at bootstrap:244
    at app.bundle.8eff2465da13d1c41817.js:1

**Comment by jwitos** [comment] 2019-09-30 15:41
Thanks @zhaoyu162, can you check then with browser extensions turned off or with different browser?

**Comment by zhaoyu162** [comment] 2019-10-01 00:55
Thank you @jwitos !
I tried another browsers but the same errors. And everytime I navigate to http://localhost:3000, I would get a message box on the top of window, it says: 
"😭: hot update was not successful
(1/1)
hot update failed for module "./App.js". Last file processed: "./OHIFStandaloneViewer.js".“”

What happend to it? 😭

**Comment by swederik** [comment] 2019-10-01 07:23
> Hi @jwitos , in debugger I still get this error for your linke as my local page previousely:
> t.getActions is not a function
> at new e (TouchBackend.js:240)
> at Mc (index.js:5)
> at Sc (viewerbaseDragDropContext.js:13)
> at Object. (OHIFStandaloneViewer.js:235)
> at a (bootstrap:68)
> at Module. (app.bundle.8eff2465da13d1c41817.js:3082)
> at a (bootstrap:68)
> at bootstrap:244
> at app.bundle.8eff2465da13d1c41817.js:1

I just pushed a fix for this in https://github.com/OHIF/Viewers/pull/982. Thanks for posting the issue!

And thanks to you too @jwitos for letting us know about https://github.com/OHIF/Viewers/issues/979. I was running into that issue as well but never thought that it could be a browser extension issue.

**Comment by swederik** [comment] 2019-10-01 09:47
Closing because this should be fixed now.

I'm not sure about this:

> hot update failed for module "./App.js". Last file processed: "./OHIFStandaloneViewer.js".“”

but it sounds very familiar. I think @dannyrb fixed that a while ago?

**Closed by swederik** 2019-10-01 09:47 UTC
Labels: Awaiting Reproduction, Community: Question :question:

**Comment by zhaoyu162** [comment] 2019-10-01 10:39
Yes，it is fixed now！
Thank you @swederik and others.
