### ISSUE TITLE
After changing the CT or PET in TMTV mode the coronal and sagital images zoom way in (turn grey) [Bug] 

### ISSUE THREAD

**Issue by BrandonDatUHN** [OHIF/Viewers#3758] opened 2023-11-02 15:25 UTC
### Describe the Bug

When viewing PET-CT images in TMTV mode changing the PET or CT using drag and drop causes the coronal and sagittal frames to zoom so far in that they appear to have disappeared entirely.

https://watch.screencastify.com/v/utGfh9WB1dyaMYrBst2n

### Steps to Reproduce

1) Go to https://viewer.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339 or any of the other PET-CT series on OHIF demo v 3.7
2) undock the thumbnails panel
3) drag the NAC PET or a different CT than the one selected into the appropriate frame of the TMTV grid
4) Coronal and sagittal panels will zoom way in so they appear grey or black
![image](https://github.com/OHIF/Viewers/assets/112980389/6eb73cd9-2f99-4baa-b7ee-7faf03b77cf4)
5) zoom back out on the panel to reveal the image is actually zoomed way in (and shifted slightly)
![image](https://github.com/OHIF/Viewers/assets/112980389/622cabbd-4592-4a39-bfd7-2a6c1088650a)

### The current behavior

When switching the CT or PET series in TMTV mode using drag and drop the coronal and sagittal panels zoom way in so that they appear as a single colour/voxel

### The expected behavior

After switching panels the coronal and sagittal should load at the same zoom level as the axial following the same behaviour as when first loading the TMTV hanging protocol

### OS

Windows 10

### Node version

whatever is on OHIF demo

### Browser

Both Edge Version 118.0.2088.76 (Official build) (64-bit) and Chrome Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by salimkanoun** [comment] 2023-11-02 16:31
Yes I confirm this bug, this is due to an erroneous zoom and pan and probably due to setOrientation API on volume viewport (I guess when you change the display set the HP service call this API)

The same bug is visible when you call the setOrientation API on volume viewport,
Interestingly this happen on the first call on the setOrientation API the zoom and pan are lost
if you call immediatly a second time this API the zoom and pan are properly restaured

**Comment by sedghi** [comment] 2023-11-02 17:01
@salimkanoun Can we reproduce this in cornerstone examples?

**Comment by salimkanoun** [comment] 2023-11-02 17:08
I guess we could see it in this one but seems broken, https://www.cornerstonejs.org/live-examples/volumeviewportorientation

I'm missing time to fix it, but i think by activating the zoom tool in this example, changing the zoom manuall and chaging orientation should duplicate the problem

**Comment by sedghi** [comment] 2023-11-02 17:39
I fixed that example (will push soon) but seems like it is not what you suggested for reproducible steps. I think it is related to the synchronizers

**Comment by salimkanoun** [comment] 2023-11-02 18:14
Hum possible we changed the camera orientation while we had 3 orthogonal viewport synced in position

**Comment by BrandonDatUHN** [comment] 2023-11-09 16:55
Any updates on this one?  Looks to still be present in v3.8.0-beta.10

**Comment by sedghi** [comment] 2024-01-09 18:02
This is fixed in dev branch just FYI

**Comment by sedghi** [comment] 2024-05-01 17:14
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.

**Closed by sedghi** 2024-05-01 17:14 UTC
Labels: fixed-in-dev-await-release
