### ISSUE TITLE
2D MPR not working on Safari

### ISSUE THREAD

**Issue by dma123** [OHIF/Viewers#2005] opened 2020-08-24 06:52 UTC
I am having issues with the 2D MPR functionality in Safari:
![Screen Shot 2020-08-24 at 4 48 58 pm](https://user-images.githubusercontent.com/4858007/91012723-e5b34480-e629-11ea-9ac7-f88874d0098b.png)

The same study loads perfectly fine if I use Chrome:
![Screen Shot 2020-08-24 at 4 49 05 pm](https://user-images.githubusercontent.com/4858007/91012743-ef3cac80-e629-11ea-9843-7707fb60ebf8.png)

I am using Safari 13.1.2 (14609.3.5.1.5). I built the viewer using the current master build (ohif/viewer@4.5.1).

**Comment by pieper** [comment] 2020-08-24 15:56
Thanks for the report.  I can reproduce this on Safari Version 13.1.2 (15609.3.5.1.3) using this link:

https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170125113417.1

@fedorov this also occurs in the IDC viewer.  I marked it as candidate and we can discuss whether it's a priority.

**Comment by JamesAPetts** [comment] 2020-10-12 09:46
So after a bunch of testing I realised this was only happening on CTs, and wasn't due to strange array sizes or anything. 

Data inserted in react-vtkjs-viewport had no difference between browsers, and I could get individual slices of the problematic data to render using the vtkImageSlice.

Turns out the issue is WebGL 1 and large textures:

https://github.com/Kitware/vtk-js/blob/acd940c9eb35efde4d16ffe2946ae31fe1d02507/Sources/Rendering/OpenGL/Texture/index.js#L1166

The max texture size is throttled here to stop the context from throwing errors, but this means not all of the data is being copied fully, this will happen with any large dataset.

Unfortuantely turning on Safari's experimental "Web GL 2.0" feature does not help here, as safari's implementation is far from complete.

So it looks like there is no easy fix for this. We could detect the browser being used and the volume size, and throw a warning when MPR is used or something?

**Comment by pieper** [comment] 2020-10-12 15:20
Yes, it sounds like detecting the issue and displaying a warning is the best we can do here.  Kind of a shame, but not really under our control.

**Comment by fedorov** [comment] 2020-11-02 17:28
@pieper do we have the fix above in the IDC?

**Comment by pieper** [comment] 2020-11-02 18:28
No, I don't believe anything has been implemented yet.  Detecting the browser and bringing up a warning still seems like the best thing.  To me the correct implementation would be to detect the issue at the lowest level (vtk.js) and propagate the information up through the layers and present it to the user at the application level.  But maybe the best short-term would be just to detect Safari in the IDC viewer and generate a warning.

**Comment by fedorov** [comment] 2020-11-02 18:34
I mean, did #2106 make it into the IDC fork?

**Comment by pieper** [comment] 2020-11-02 18:51
Yes, at the OHIF level: https://github.com/ImagingDataCommons/Viewers/commits/idc-ohif-2020-10-15

**Comment by fedorov** [comment] 2020-11-02 19:01
Thanks! @wlongabaugh FYI

**Comment by sedghi** [comment] 2023-10-13 14:44
Please review the latest code in the master branch. This issue might have been resolved. If it persists, kindly reopen the issue with updated details. 

Try viewer-dev.ohif.org instead of viewer.ohif.org
Our `viewer.ohif.org` is deployed from `release` branch while `viewer-dev.ohif.org` is our `master ` branch
Read more about branch explanations here https://docs.ohif.org/development/getting-started#developing

**Closed by sedghi** 2023-10-13 14:44 UTC
Labels: IDC:candidate
