### ISSUE TITLE
sometimes StudyInstanceUID becomes null

### ISSUE THREAD

**Issue by DraconPern** [OHIF/Viewers#81] opened 2017-06-15 04:54 UTC
I20170614-23:10:55.116(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614
I20170614-23:10:55.135(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614: 11ms
I20170614-23:11:57.180(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20000101-20170614
I20170614-23:11:57.202(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20000101-20170614: 22ms
I20170614-23:12:00.978(-5)?  GetStudyMetadata(%s) 1.2.124.113532.80.22155.25184.20150212.94832.415279
I20170614-23:12:00.995(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies/1.2.124.113532.80.22155.25184.20150212.94832.415279/metadata
I20170614-23:12:01.157(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies/1.2.124.113532.80.22155.25184.20150212.94832.415279/metadata: 168ms
I20170614-23:12:17.886(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614
I20170614-23:12:17.896(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614: 7ms
I20170614-23:12:17.904(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614
I20170614-23:12:17.912(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20170614-20170614: 10ms
I20170614-23:12:29.885(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20000101-20170614
I20170614-23:12:29.905(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies?includefield=00081030%2C00080060&StudyDate=20000101-20170614: 19ms
I20170614-23:12:34.681(-5)?  GetStudyMetadata(%s) null
I20170614-23:12:34.685(-5)? http://asuna.frontmotion.local:8042/dicom-web/studies/null/metadata
I20170614-23:12:35.532(-5)? Exception while invoking method 'GetStudyMetadata' Error: We only support json but "" was sent by the server
I20170614-23:12:35.533(-5)?     at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.4.2_3.75keg0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170614-23:12:35.534(-5)?     at packages/meteor.js:213:24
I20170614-23:12:35.535(-5)?     at Object.DICOMWeb.getJSON (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:73:20)
I20170614-23:12:35.535(-5)?     at Object.Services.WADO.RetrieveMetadata (packages/ohif:study-list/server/services/wado/retrieveMetadata.js:342:27)
I20170614-23:12:35.535(-5)?     at [object Object].GetStudyMetadata (packages/ohif:study-list/server/methods/getStudyMetadata.js:20:34)
I20170614-23:12:35.536(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
I20170614-23:12:35.536(-5)?     at packages/ddp-server/livedata_server.js:711:19
I20170614-23:12:35.537(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170614-23:12:35.539(-5)?     at packages/ddp-server/livedata_server.js:709:40
I20170614-23:12:35.539(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170614-23:12:35.540(-5)?     - - - - -
I20170614-23:12:35.541(-5)?     at ClientRequest.<anonymous> (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:47:22)
I20170614-23:12:35.541(-5)?     at ClientRequest.g (events.js:260:16)
I20170614-23:12:35.541(-5)?     at emitOne (events.js:77:13)
I20170614-23:12:35.542(-5)?     at ClientRequest.emit (events.js:169:7)
I20170614-23:12:35.542(-5)?     at HTTPParser.parserOnIncomingClient (_http_client.js:433:21)
I20170614-23:12:35.543(-5)?     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
I20170614-23:12:35.543(-5)?     at Socket.socketOnData (_http_client.js:322:20)
I20170614-23:12:35.544(-5)?     at emitOne (events.js:77:13)
I20170614-23:12:35.545(-5)?     at Socket.emit (events.js:169:7)
I20170614-23:12:35.545(-5)?     at readableAddChunk (_stream_readable.js:153:18)
I20170614-23:12:40.281(-5)?  GetStudyMetadata(%s) null

**Comment by swederik** [comment] 2017-06-15 06:48
Just to be clear, what were you doing when you recorded this log? It looks like you went from study list to load a study in the viewer? Is that correct? Did you double-click a study in the study list?

**Comment by DraconPern** [comment] 2017-06-16 08:11
Yup, just doubled clicked a study in the list.  The study never came up.  I just see spinning circle.

**Comment by swederik** [comment] 2017-06-16 08:13
Are you connecting to your PACS over with DIMSE or DICOMWeb? Anything special about how the study displays in the list?

**Comment by DraconPern** [comment] 2017-06-16 21:21
It was master of the viewers and latest release of orthanc.  Connected over dicomweb.  It was doing this for every study.

**Comment by nicejwjin** [comment] 2017-08-30 08:05
I used publicOrthancDICOMWeb.json settings and got same issue.
The url request on the top of the log shows this error 
{
   "HttpError" : "Not Found",
   "HttpStatus" : 404,
   "Message" : "Unknown resource",
   "Method" : "GET",
   "OrthancError" : "Unknown resource",
   "OrthancStatus" : 17,
   "Uri" : "/dicom-web/studies"
}

and http://34.224.187.57:8042/dicom-web  common url was returns same things,
so I wonder the public uri would be changed or not..

Is there any idea for this?

Thanks.




I20170830-16:53:34.126(9)? http://localhost:8042/dicom-web/studies?includefield=00081030%2C00080060
I20170830-16:53:34.477(9)? Exception while invoking method 'StudyListSearch' Error: We only support json but "" was sent by the server
I20170830-16:53:34.477(9)?     at Object.Future.wait (/Users/jwjin/.meteor/packages/meteor-tool/.1.5.0.1hv5m4c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170830-16:53:34.478(9)?     at packages/meteor.js:213:24
I20170830-16:53:34.478(9)?     at Object.DICOMWeb.getJSON (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:77:20)
I20170830-16:53:34.478(9)?     at Object.Services.QIDO.Studies (packages/ohif:study-list/server/services/qido/studies.js:94:27)
I20170830-16:53:34.479(9)?     at [object Object].Meteor.methods.StudyListSearch (packages/ohif:study-list/server/methods/studylistSearch.js:20:34)
I20170830-16:53:34.479(9)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170830-16:53:34.480(9)?     at packages/ddp-server/livedata_server.js:719:19
I20170830-16:53:34.480(9)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170830-16:53:34.481(9)?     at packages/ddp-server/livedata_server.js:717:40
I20170830-16:53:34.481(9)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170830-16:53:34.481(9)?     - - - - -
I20170830-16:53:34.481(9)?     at ClientRequest.<anonymous> (packages/ohif:dicom-services/server/DICOMWeb/getJSON.js:50:22)
I20170830-16:53:34.481(9)?     at ClientRequest.g (events.js:260:16)
I20170830-16:53:34.482(9)?     at emitOne (events.js:77:13)
I20170830-16:53:34.482(9)?     at ClientRequest.emit (events.js:169:7)
I20170830-16:53:34.482(9)?     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
I20170830-16:53:34.482(9)?     at HTTPParser.parserOnHeadersComplete (_http_common.js:97:23)
I20170830-16:53:34.483(9)?     at Socket.socketOnData (_http_client.js:322:20)
I20170830-16:53:34.483(9)?     at emitOne (events.js:77:13)
I20170830-16:53:34.483(9)?     at Socket.emit (events.js:169:7)
I20170830-16:53:34.484(9)?     at readableAddChunk (_stream_readable.js:153:18)

**Comment by swederik** [comment] 2017-10-19 15:47
I think the 'public' server is actually not being run anymore.

As for the original issue, I can't seem to reproduce it so I'll close the issue. If you can find any more information or can reliably recreate the issue please reopen. Thanks!

**Closed by swederik** 2017-10-19 15:47 UTC
Labels: bug, dicomweb
