### ISSUE TITLE
[Bug] Failed to transform frame

### ISSUE THREAD

**Issue by ahan** [OHIF/Viewers#3865] opened 2023-12-21 09:19 UTC
### Describe the Bug

there is a javascript error, "Uncaught (in promise) Error: Failed to transform frame: RuntimeError: null function or function signature mismatch"

### Steps to Reproduce

1. Go to the below links
[viewer-dev](https://viewer-dev.ohif.org/microscopy?StudyInstanceUIDs=2.25.103659964951665749659160840573802789777)
2. Errors happened lead to image load failed

### The current behavior

image cannot load

![image](https://github.com/OHIF/Viewers/assets/654880/aab2ee6a-9d23-4d7b-87dd-4af20c62b5bc)

### The expected behavior

load image successfully

### OS

macOS 14.2

### Node version

v20

### Browser

Chromium 120.0.6099.109

**Comment by sedghi** [comment] 2024-01-08 18:07
Hmmm not sure what has happened, thanks for the report, I will check it

**Comment by sedghi** [comment] 2024-01-08 18:07
seems to work in viewer.ohif.org

**Comment by sedghi** [comment] 2024-01-09 21:57
Seems like the issue was introduced when yarn.lock was removed and re-added in this PR https://github.com/OHIF/Viewers/pull/3847/files

**Comment by sedghi** [comment] 2024-01-10 21:16
Seems like the issue is a bug in `dicomweb-client` that is introduced with this PR https://github.com/dcmjs-org/dicomweb-client/commit/4cff356893a42f58ec69dc9d0121ca6bb07d20d4

Meanwhile you can revert to 0.10.2 and enjoy SM until a proper fix is introduced

CC: @salimkanoun @Celian-abd it was not yarn lock issues at the end of the day, it was an actual bug

**Comment by sedghi** [comment] 2024-05-01 17:11
We just release the OHIF 3.8, you can find more details here https://ohif.org/release-notes/3p8/
If you still encounter this issue in 3.8, please re-open this.

**Closed by sedghi** 2024-05-01 17:11 UTC
Labels: Bug Verified, fixed-in-dev-await-release
