### ISSUE TITLE
Local upload cannot be used.

### ISSUE THREAD

**Issue by luohao110** [OHIF/Viewers#1254] opened 2019-12-05 05:45 UTC
![image](https://user-images.githubusercontent.com/48583201/70207260-349c0f80-1765-11ea-8479-6db1daa7921d.png)
The console reported an error. File upload and folder upload cannot be clicked, and not "cursor:pointer;"

**Comment by swederik** [comment] 2020-01-17 13:59
@mirnasilva Can you re-test this? I think it's been fixed.

**Comment by mirnasilva** [comment] 2020-01-17 15:23
Hi @swederik , I re-tested this on `dev` and `production` environments and the functionality is working as expected. The issue is not reproducible anymore.
I'm closing this ticket. Thanks!

**Closed by mirnasilva** 2020-01-17 15:23 UTC
Labels: Community: Report :bug:, Triage :white_flag:
