### ISSUE TITLE
[Bug] 3.8 recovery

### ISSUE THREAD

**Issue by sedghi** [OHIF/Viewers#4087] opened 2024-05-06 14:03 UTC
### Describe the Bug

Here are the bugs that need to be fixed in the 3.8.1 release 

 
- [x] tmtv cannot use the threshold tool
- [x] https://github.com/OHIF/Viewers/issues/4046
- [x] https://github.com/OHIF/Viewers/issues/4081
- [x] https://github.com/OHIF/Viewers/issues/4132
- [x] https://github.com/OHIF/Viewers/pull/4090
- [x] THe tmtv issue when sometimes the fusion has wrong inverted
- [x] https://github.com/OHIF/Viewers/issues/4158

**Comment by sedghi** [comment] 2024-05-06 14:03
Threshold tool tmtv does not work

![Uploading CleanShot 2024-05-06 at 10.03.44@2x.png…]()

**Comment by sedghi** [comment] 2024-05-10 13:49
Add the types

**Comment by sedghi** [comment] 2024-05-16 14:15
https://github.com/OHIF/Viewers/issues/4132

**Comment by tzuccher** [comment] 2024-05-30 09:04
**3.8.1 Bug Found while trying to reproduce #4046 - did not even get as far as the steps in 4046: 
Segmentation Mode Select Add Segmentation = Black Viewports**

Found in version (https://ohif-viewer-381-rc1.netlify.app/): 3.8.1, Commit hash: 1dcdc9dabe9d4179f223912d6adc00bc95629a85

Steps:

1. Select study HCC_004 and select the Segmentation button
2. From the viewer page, select the Add Segmentation verbiage in the right-side panel = black viewports that i cannot scroll or do anything with them
![image](https://github.com/OHIF/Viewers/assets/143200290/888cce8f-7121-4a64-abd2-f13101ab98a1)

**Comment by tzuccher** [comment] 2024-05-30 09:22
**3.8.1 Bug Found while testing 4046:
Segmentation Mode drag in SEG series = black viewport where I cannot see the image or existing segmentations

Found in version (https://ohif-viewer-381-rc1.netlify.app/): 3.8.1, Commit hash: https://github.com/OHIF/Viewers/commit/1dcdc9dabe9d4179f223912d6adc00bc95629a85

Steps:

1. Select a SEG study and select the Segmentation button to go to the viewer screen - i used PCAMPMRI...
2. Scroll to the bottom of the study panel and dragged the last SEG item into viewport C - clicked yes = all 4 viewports went black
3. Clicking in viewport C = errors in console
![image](https://github.com/OHIF/Viewers/assets/143200290/81d7e6e6-54b0-4d68-b428-a3e48abc37ea)

**Comment by tzuccher** [comment] 2024-05-30 09:38
Note that selecting a SEG study with the Basic Viewer mode (instead of the Segmentation mode), and then dragging in the SEG item into a viewport still produced a black viewport but, i was able to select a different layout option that seemed to produce images. After this, i was able to load in Segmentation mode without getting the black viewports - not sure what these steps did to help resolve the2 issues above that i reported...

**Comment by tzuccher** [comment] 2024-05-30 09:54
Testing #4046 now that i can get the SEG to work again... (with 3.8.1 testing: 3.8.1, Commit hash: 
1dcdc9dabe9d4179f223912d6adc00bc95629a85) 
As described in the issue, using study WaterPhantom, there seems to be no issue or with  study ACRIN ... with 934 instances,

**Comment by tzuccher** [comment] 2024-05-30 10:02
new issue?
**Segmentation mode: within the viewport zoom in on the image = can no longer add segment shapes to any images**

Found in version (https://ohif-viewer-381-rc1.netlify.app/): 3.8.1, Commit hash: https://github.com/OHIF/Viewers/commit/1dcdc9dabe9d4179f223912d6adc00bc95629a85

Steps:
1. Select a study and the Segmentation button
2. Click into a viewport, select Add Segment verbiage
3. Select brush and create shapes on image
4. Zoom in on the image
5. Select the brush tool again and attempt to create a shape on the same or different viewport = i can no longer create shapes
![image](https://github.com/OHIF/Viewers/assets/143200290/88b84d3e-27be-438b-815f-a8a638f65835)

**Comment by sedghi** [comment] 2024-06-03 14:16
https://ohif-viewer-381-rc2.netlify.app/

**Comment by tzuccher** [comment] 2024-06-03 18:25
Test results from initial view from: https://ohif-viewer-381-rc2.netlify.app/
Note: opened a new Chrome Incognito window for each issue being verified

**Issue: tmtv cannot use the threshold tool**
**Pass with the following steps:**
1. Select study: ACRIN...with 934 instances and selected the Total Metabolic Volume button
2. Clicked into the PT axial viewport 
3. Selected the Rectangle ROI Threshold tool and created shape on image = was able to create shape without receiving Something Went Wrong message
4. Selected Add segmentation verbiage
5. Selected Run button = created red shading on all viewports, in area where the rectangle was created on the PT axial viewport

**Issue: #4046** 
**RESULT = Failed testing with the following steps for two scenarios**
**4046 Scenario One**
1. Select study: Water Phantom and select the Segmentation button
2. From the 2x2 layout with Viewport A active, select the +Add segmentation verbiage = nothing happens and there is an uncaught error in the console
![image](https://github.com/OHIF/Viewers/assets/143200290/e88a26fc-7cff-4150-88be-eb3af16f6ae1)

**4046 Scenario Two**
1. Select study CT/SEG HCC_004 and select the Segmentation button
2. From the viewer page, select the Add Segmentation verbiage in the right-side panel = also same as above, nothing happens with uncaught error in the console
![image](https://github.com/OHIF/Viewers/assets/143200290/373bdfe1-8c48-4164-9a58-e2e50ce276a9)

**Issue #4132** 
**RESULT = Passed with the following steps:**
1. Select a SEG study and select the Segmentation button to go to the viewer screen - I used PCAMPMRI...
2. Scroll to the bottom of the study panel and drag the last SEG item into viewport C - clicked yes = all 4 viewports filled accordingly with the images + existing segmentations
3. I was able to repeat step 2 for all three seg items in the study panel
4. Selected the Segmentation drop-down menu and all 3 seg items appeared and I could select them successfully
5. Was also able to add a new segment without issue
6. I also went back to the study list page and selected the same study in basic viewer mode = I was able to drag into the active viewport the SEG items & view them without issue

**Issue #4158** 
**RESULT = passed with the following steps:**
1. load T2 Weighted Axial Segmentation = displays with segmentation panel populated
2. load DCE Subtraction Segmentation = displays with segmentation panel populated
3. load Apparent Diffusion ... item = displays with a segmentation panel populated
4. on the segmentation panel, load the segmentation dropdown, see all 3 options and select each.
5. Select the Layout tool menu and select different options = the screen layout will change without error no matter what option is selected

**Comment by tzuccher** [comment] 2024-06-03 18:56
Retested the noted issues and all steps noted pass with the latest build in rc3: https://ohif-viewer-381-rc3.netlify.app/

Tested the following with passing results (steps noted in comment above) on a mac (sonoma 14.5) + chrome browser (v125)

1. Passed Issue: tmtv cannot use the threshold tool
2. Passed Issue: https://github.com/OHIF/Viewers/issues/4046
3. Passed Issue https://github.com/OHIF/Viewers/issues/4132
4. Passed Issue https://github.com/OHIF/Viewers/issues/4158
5. Passed new issue recorded May 30th (above): Segmentation mode: within the viewport zoom in on the image = can no longer add segment shapes to any images

**Comment by tzuccher** [comment] 2024-06-05 17:09
Additional issues noted that required new rc builds: 

1. Capture tool was not displaying image (fixed in rc4)
2. US study: Cardiac US images were red in the basic viewer (fixed in rc5)

**Comment by tzuccher** [comment] 2024-06-05 17:12
New issue found on ohif-viewer-381-rc5, 3.8.1 Commit hash: 1dcdc9dabe9d4179f223912d6adc00bc95629a85on a mac (sonoma 14.5) + chrome browser (v125) - https://ohif-viewer-381-rc5.netlify.app/

**TMTV MIP image lost when rectangle ROI is created & run twice and then MIP rotated**
Steps to recreate:
1. Select ACRIN...with 934 instances and the TMTV button
2. Clicked into the PT axial image and created a Rectangle ROI shape
3. Pressed Add segmentation verbiage and then the Run button = the shape filled with red shading as expected
4. Clicked on MIP, rotated and double-clicked to go into 1x1 - double-clicked again to go into TMTV layout
5. Created a new rectangle shape on PT axial and clicked Run button again = the red shading changed to the new rectangle
6. Clicked on the Add segmentation verbiage = Segmentation 2 displayed  but also noticed the MIP moved a bit within the viewport
7. Clicked on the MIP image to rotate and it disappeared from the viewport
![image](https://github.com/OHIF/Viewers/assets/143200290/bc023177-7769-4856-967f-9ebad90c4509)

**Comment by tzuccher** [comment] 2024-06-10 16:58
I am also seeing in: https://ohif-viewer-381-rc5.netlify.app/
The hotkey 'z' is not longer working on the viewer screen. It is configured but not doing anything when the z key is pressed.

It does look to be working in prod version 3.8
![image](https://github.com/OHIF/Viewers/assets/143200290/df8455b6-76f1-4e05-99b8-77df92e5207d)

**Comment by sedghi** [comment] 2024-06-11 18:16
As discussed we will address these in the next version

**Closed** 2024-06-14 17:02 UTC
