### ISSUE TITLE
[Bug] VOI settings lost when closing fullscreen volume viewport (Regression in 3.8 beta) 

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#4011] opened 2024-03-29 21:22 UTC
### Describe the Bug

In the 3.8 beta version, when opening a study in a volume viewport Hanging protocol, the VOI setting is lost when leaving a full screen viewport.
The VOI settings was not lost in 3.7

I briefly discuss this with @sedghi until I identified that this bug is actually a regression.

This bug affects HP with volume viewport, but not HP using stack viewport

### Steps to Reproduce

1. Go to https://viewer-dev.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7695.4007.324475281161490036195179843543
2. Open MPR mode
3. Press 4 to activate Bone VOI preset
4. Double click on any viewport to go full screen
5. Double click to exit full screen
6. => here is a bug, the VOI is reseted to soft tissue which is the default VOI, the Bone VOI preset is lost.

### The current behavior

VOI is reseted at full screen exit (probably reset to HP default)

### The expected behavior

Current VOI parameter should be kept to not interrupt what the physician was focusing on.

The same procedure on the 3.7 release on https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7695.4007.324475281161490036195179843543 dosen't have the bug (Bone VOI is beeing kept)

### OS

Linux

### Node version

Node 20

### Browser

Chrome latest

**Comment by IbrahimCSAE** [comment] 2024-04-03 10:42
https://github.com/OHIF/Viewers/blob/d8f66856ccc03fc8cfb0bf67315a3068c96c39bb/extensions/cornerstone/src/services/ViewportService/CornerstoneViewportService.ts#L187

The issue is here, since presentation is map, object entries will always return an empty array, a fix can be something like

```js
    if (lutPresentation) {
      const { presentation } = lutPresentation;
      if (viewport instanceof VolumeViewport) {
        // if its map
        if (presentation instanceof Map) {
          presentation.forEach((properties, volumeId) => {
            viewport.setProperties(properties, volumeId);
          });
        } else {
          viewport.setProperties(presentation);
        }
      } else {
        viewport.setProperties(presentation);
      }
    }
  ```
should be an easy fix, will get it merged.

**Comment by salimkanoun** [comment] 2024-04-03 11:34
Thank you so much !

**Comment by salimkanoun** [comment] 2024-04-06 15:22
@sedghi @IbrahimCSAE , it's better thanks, but there still a problem,

Go to TMTV mode, https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.871108593056125491804754960339
Double click on a fused viewport to make it full screen
Double click to return to main view

You will see the VOI is modified, the image is blue only, wich is the first colors of the colormap.

**Closed** 2024-04-30 06:46 UTC
Labels: fixed-in-dev-await-release
