### ISSUE TITLE
UserPreferences issues with translation and hotkeys

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#1193] opened 2019-11-15 22:29 UTC
## Bug Report

A couple of bugs were found and they will be described below:

### Issue 1: Translation not cancelled

On UserPreferences modal, if user selects another language (i.e. Spanish) and clicks on `Cancel`, the toolbar and some of the other page elements will be translated into the selected language, even though the user cancelled the language selection. This is happening on **StudyList page** and on **Viewer page**.

**Steps to Reproduce:**

1. Open Preferences modal
2. Go to General tab
3. Select `Spanish` language
4. Verify that the header and toolbar gets translated behind the modal
5. Click on `Cancel` button
6. Verify that the header and toolbar remain in Spanish, even though the user cancelled the language selection.

### Issue 2: Options overlay not being translated

1. On StudyList page, if user selects another language on the Preferences modal, the Options overlay is not being translated. After selecting Spanish and navigating to Viewer page, the Options overlay gets partially translated to Spanish and won't change back to English, even if user selects English on Preferences modal. 

2. The option `Preferences` is being displayed only in English and is not being translated.

**Study List page**
<img width="506" alt="Screen Shot 2019-11-15 at 18 30 35" src="https://user-images.githubusercontent.com/13245529/68977519-31051080-07d7-11ea-939a-96a4cc0fe953.png">

**Viewer page**
<img width="431" alt="Screen Shot 2019-11-15 at 18 31 28" src="https://user-images.githubusercontent.com/13245529/68977516-2e0a2000-07d7-11ea-82ff-b5e2df35b468.png">

### Issue 3: "Reset to Defaults" button closes the modal

If user clicks on "Reset to Defaults" button, the Preferences modal is closed and the user has to open it again to make sure it restored default values. 

**Acceptance Criteria:** 

1. After user clicks on "Reset to Defaults" button, the values should be restored and the modal should remain open.
a) If user clicks on "Save" button, then the default values are saved and the modal is closed.
b) If user clicks on "Cancel" button, then the default values are **not saved**, the previous values are kept and the modal is closed.

### Issue 4: No Zoom In limit for hotkeys

When user is zooming in through the mouse he/she can reach a limit of zoom. When user is zooming in by using hotkeys, there is no zooming limit.

**Expected result**
The hotkey zooming in should respect the same limit as the mouse zooming.

<img width="1297" alt="Screen Shot 2019-11-15 at 18 55 44" src="https://user-images.githubusercontent.com/13245529/68978613-08324a80-07da-11ea-9d15-03b048069877.png">

<img width="1301" alt="Screen Shot 2019-11-15 at 18 56 13" src="https://user-images.githubusercontent.com/13245529/68978612-08324a80-07da-11ea-9599-83258836d17c.png">

### Issue 5: Hotkeys with "shift" not being detected on viewport

On Preferences modal, if user tries to add hotkey `+` without using a Numpad, the Preferences modal will recognize the pressed hotkeys as `shift+ +`, but if the user tries using the same key combination on the viewport, the hotkey detected is `+` and not `shift+ +`. 

The same happens when user adds any hotkey that is a combination of `shift` + `<secondary symbol>`, where a secondary symbol can be considered as: `+, _, ), (, *, &, %, $, #, @, !`. For example:

Preference modal hotkey detected: `Shift+(`
Hotkey detected on viewport: `(`

### Issue 6: "Reset to Defaults" button doesn't reset selected language

On Preferences modal, if user selects another language (Spanish) and clicks on "Reset to Defaults", the language is not restored to English.

**Steps to Reproduce:**

1. Open User Preferences modal
2. Click on General tab and select language "Spanish" 
3. Click on Save button
4. Open User Preferences modal again
5. Go to General tab and click on "Restore to Defaults" button

**Actual Result:**
1. Verify that the content still in Spanish. 
2. Verify that the selected language in the dropdown still as Spanish

**Expected Result:**
1. The content of the application should be changed back to English
2. The selected language in the dropdown should be changed back to English

**Acceptance Criteria:**
1. After user clicks on "Reset to Defaults" button, the values in the active tab should be restored and the modal should remain open.
a) If user clicks on "Save" button, then the default values are saved and the modal is closed.
b) If user clicks on "Cancel" button, then the default values are not saved, the previous values are kept and the modal is closed.

### Issue 7: "Save" button doesn't save changes on both tabs

On User Preferences modal, if user makes changes on both tabs (Hotkeys and General) and clicks on "Save" button, only the content of the active tab is being saved. 
In this scenario, if the user wants to make changes on both tabs, he/she has to go to Hotkeys tab update it and save. Then open the User Preferences again, go to General tab, update it and save.

**Acceptance Criteria:**
To improve user experience: 
1. "Save" button should save all changes made in both tabs and close the Preferences modal
2. "Reset to Defaults" button should reset the values only on the active tab and the Preferences modal should stay open.
   a) If user clicks on "Save" button, all changes made in both tabs should be saved and Preferences modal should be closed.
   b) If user clicks on "Cancel" button, all changes will be ignored (default values won't be saved), and Preferences modal should be closed.
3. "Cancel" button should ignore all changes made in both tabs and close the Preferences modal.

**Comment by dannyrb** [comment] 2019-11-18 14:06
Assigning @rodrigolabs for at least the first issue of this ticket.

**Comment by ladeirarodolfo** [comment] 2019-11-19 21:39
@rodrigolabs to help you out..
please use the following branches:
https://github.com/OHIF/Viewers/pull/1203
https://github.com/OHIF/Viewers/pull/1150

Branches above will partial fix some of the issues. (I`m about to finish its reviews)

also I found out an issue on language configuration based on changing language from userpreference modal.

Looks like there is something missing on i18n set up.
See the image below. There is no resource for given lng ('eng'). But if instead I hack this object doing something like: `this.options.resources["en"] = this.options.resources["en-US"]`

<img width="1376" alt="Screen Shot 2019-11-19 at 18 31 44" src="https://user-images.githubusercontent.com/39910206/69188640-afc1bc80-0afb-11ea-99d5-8519cd738f0d.png">

**Comment by dannyrb** [comment] 2019-12-02 04:20
The bulk of these issues have been addressed in a recent merge. We intend to do some clean-up on `12/2` that will create related issues. If anyone notices a regression, please reference this issue in your new ticket/issue ^_^

**Closed by dannyrb** 2019-12-02 04:20 UTC
Labels: Bug: Verified :bug:
