### ISSUE TITLE
How to save measurements and annotations for a DICOM hosted in Orthanc?

### ISSUE THREAD

**Issue by kkmehta03** [OHIF/Viewers#1907] opened 2020-07-17 10:24 UTC
Hello! 
As the title says, I'm trying to find a way to save the annotations to the dicom files hosted on Orthanc server. 
I referred [this](https://github.com/OHIF/Viewers/issues/1102), [this](https://github.com/OHIF/Viewers/issues/758) and [this](https://github.com/OHIF/Viewers/issues/1800) issue, but I'm not sure how to implement the feature for Orthanc itself. Should some code changes be done on the back-end or is there a way to make the change from the front end?
Edits : Adding screenshots to describe the exact issue
1. Below image shows that the segmentation is getting done, and the measurements are successfully saved
![issue_screenshot_1](https://user-images.githubusercontent.com/25249564/88326210-6e954280-cd43-11ea-80fa-e34cb6428478.png)
2. Below image shows on refresh, that the segmentation is gone and so are the measurements:
![issue_screenshot_2](https://user-images.githubusercontent.com/25249564/88326274-7f45b880-cd43-11ea-885d-60e185370d84.png)
3. For some reason, the annotations are going inside orthanc's server as a new instance, as shown below:
![issue_screenshot_3](https://user-images.githubusercontent.com/25249564/88326345-92588880-cd43-11ea-819f-eed1c0d87a58.png)

Is there any way to fix this? Instead of getting saved as an instance, can it be shown as expected, in the first screenshot? 
Also, if the study list is not refreshed, the annotations on the dicom remain as expected. 

Could anyone give some hints or documentation link to achieve this?

**Comment by ranasrule** [comment] 2020-07-24 12:03
this is a known issue when saving annotations to Orthanc

**Comment by ranasrule** [comment] 2020-07-24 12:41
This is a known bug in OHIF when saving annotations to Orthanc

**Comment by KhyatiMehta3** [comment] 2020-07-24 13:38
@ranasrule Would you please point me to an appropriate fix? Is there any way to save it properly like an extension? I'm referring to a couple of issues here, but not finding any leads

**Comment by ranasrule** [comment] 2020-07-24 14:02
> @ranasrule Would you please point me to an appropriate fix? Is there any way to save it properly like an extension? I'm referring to a couple of issues here, but not finding any leads

I haven't found a resolution myself. I reported this issue a while back at the following link and free others have too but nothing has been done about it.

https://github.com/OHIF/Viewers/issues/1679

**Comment by KhyatiMehta3** [comment] 2020-07-24 20:23
@ranasrule Thanks for your responses. I'm continuing the conversation there as well to resolve this.

**Comment by joweste** [comment] 2020-08-04 17:57
Hi, what I have to do to enable the feat to save  annotations?

**Comment by hleu** [comment] 2020-09-11 00:16
Hello, I ran into the same problem. How did you resolve this? Changing the docker container? 
I am very new to this so I d like to ask for more details about how to save annotations. Right now I am trying to create a tool that can save measurements from a point in a CT scan <x,y> (like values from Probe tools) as well as some identifications like patient ID, date, into a csv file. I was looking at this:
https://github.com/OHIF/Viewers/pull/954#issuecomment-607543229

Else, the save measurements from elliptical annotations into some form that I can read later works as well. However, when I tried to save measurements in Orthanc the measurement appeared as a container without the measurements in json file. I am not sure what I am missing to get this to work. What do you think is the best way to approach this? Thank you.

**Comment by ranasrule** [comment] 2020-09-30 19:59
measurements and annotations are still saved as a separate study in Orthanc...also measurements cant be labelled or description added

I don't know why this has been marked as closed.

**Comment by swederik** [comment] 2020-10-01 08:28
Whoops, looks like Github closed it automatically because the issue number was referenced in a merged PR.

**Comment by donghakang** [comment] 2021-05-28 07:37
I am currently using docker orthanc, postgresql and have exactly same issue. 
Did anyone try to fix the issue?

**Comment by oriashush** [comment] 2021-07-18 10:17
Is there a fix to this issue?

**Comment by luisuriarte** [comment] 2021-09-23 14:26
Hi there. So that the error does not occur, is there a way to disable saving annotations?.
Thank You
Regards

**Comment by luisuriarte** [comment] 2022-07-13 12:36
Yes.
Edit the file Viewers-master/platform/viewer/src/OHIFStandaloneViewer.css
add to end:
<code>
/*# hide measurements button start*/
#root > div.ToolbarRow > div.pull-right.m-t-1.rm-x-1 > div > div.roundedButtonWrapper:first-child {
	margin-left: 0;
	visibility: collapse;
}
/*# hide measurements button end*/
</code>

**Comment by maya-harel** [comment] 2022-07-13 15:44
> Yes. Edit the file Viewers-master/platform/viewer/src/OHIFStandaloneViewer.css add to end:
> 
> /_# hide measurements button start_/ #root > div.ToolbarRow > div.pull-right.m-t-1.rm-x-1 > div > div.roundedButtonWrapper:first-child { margin-left: 0; visibility: collapse; } /_# hide measurements button end_/

Is this something I can configure when running orthanc and ohif in docker containers? (without updating the source code)

**Comment by sedghi** [comment] 2023-10-12 20:55
This is fixed in latest master branch. 

Feel free to re-open if the issue is not resolved you think

**Closed by sedghi** 2023-10-12 20:55 UTC

**Comment by aadilakhtar3402** [comment] 2024-07-19 07:58
@kkmehta03 Hi, did you find a way to save the annotations?
