### ISSUE TITLE
Changes made to Cine FPS slider are not being reflected on viewport frequency

### ISSUE THREAD

**Issue by mirnasilva** [OHIF/Viewers#994] opened 2019-10-03 18:09 UTC
### Description

When user selects the Cine tool and drags the fps slider to a frequency different from the default, the video-images frequency on the viewport remains unchanged.
This only happens when the fps modification is performed when the video is not being under execution (Play button was not clicked).

![bug-cine](https://user-images.githubusercontent.com/13245529/66152329-a2a24a00-e5ef-11e9-8033-9283e717afb3.gif)

### Steps to Reproduce

1. Load view studies page
2. Select the Cine tool on the toolbar
3. Change the fps slider to 1 fps
4. Click on Play button
5. Verify that the velocity/frequency was not updated on the viewport
6. Click on Stop button
7. Change the fps slider to 90 fps
8. Click on Play button
9. Verify that the velocity/frequency was not updated on the viewport

### Actual Result

User is changing the video fps but these changes are not being reflected on the viewport

### Acceptance Criteria:

User should be able to play the video with selected frequency.
User should be able to change the video fps while it is being executed or while it is not being played.

**Comment by dannyrb** [comment] 2019-10-09 19:24
This issue is not reproducible in the `react-cornerstone-viewport` example here: https://react.cornerstonejs.org/grid

This leads me to believe it's an integration / app issue.

Our `CineDialog` has an `onFrameRateChanged` prop that passes a parsedFloat to it's callback.  The `ConnectedCineDialog` dispatches `setViewportSpecificData` to update the `cine` object for our `activeViewportIndex`.

Our `ConnectedCornerstoneViewport` maps that state to it's own `frameRate` prop, which is passed to our `CornerstoneViewport` component.

I'm not sure where the disconnect is, but hopefully that's enough context to take someone down the right path.

**Comment by igoroctaviano** [comment] 2019-10-09 19:53
I have tested the scenarios mentioned + some other variations and i couldn't reproduce the issue on master locally. 

*We should check deployed/testing versions.

**Comment by dannyrb** [comment] 2019-10-09 20:03
Related: https://github.com/OHIF/Viewers/issues/529

**Comment by dannyrb** [comment] 2019-10-10 12:56
This is now fixed: https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1

Our demo deployment on CI kept timing out, so the demo was behind master. We've temporarily turned off minification to make sure it deploys.

**Closed by dannyrb** 2019-10-10 12:56 UTC
Labels: Bug: Verified :bug:
