### ISSUE TITLE
MPR render failures for some ProstateX cases

### ISSUE THREAD

**Issue by pieper** [OHIF/Viewers#2418] opened 2021-05-24 15:46 UTC
## Bug Report

@sedghi pointed out that some images don't render correctly in MPR mode.  The sagittal is missing unless you slightly rotate the plane and the axial has a block missing in the upper left.  The data looks fine in Slicer and in the cornerstone mode so we suspect a bug in vtkjs or in the way ohif uses vtkjs.

### Describe the Bug

![image](https://user-images.githubusercontent.com/126077/119372163-0413a280-bc85-11eb-8ec3-7354fd42b359.png)

### What steps can we follow to reproduce the bug?

prostatex is in idc v2 release, so only accessible in testing currently:

https://.../viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.879702148497420836831435403010

**Comment by pieper** [comment] 2021-05-24 15:46
@sedghi is investigating and can add updates here.  Current plan is to aim for a pure-vtkjs replication of the issue if possible.

**Comment by fedorov** [comment] 2021-05-24 15:50
might be a duplicate of https://github.com/OHIF/Viewers/issues/2308

**Comment by pieper** [comment] 2021-05-24 15:54
> might be a duplicate of #2308

doesn't look like it.  There's no runtime error for this one.

**Comment by sedghi** [comment] 2021-05-24 16:03
I'm investigating this issue in a code-sandbox to recreate volume rendering. 
Orientation we use is:
```
 SAGITTAL: {
    sliceNormal: [1, 0, 0],
    viewUp: [0, 0, 1],
  }
```
and it seems like `sliceNormal` is causing it to happen.

**Comment by Punzo** [comment] 2021-05-25 07:50
Other issue in which the same bug has been reported: https://github.com/OHIF/Viewers/issues/2371

The issue looks like to be at vtk level and as James highlighted, other organizations has encountered it and it does not seems fixed yet. E g. For reference https://github.com/Kitware/vtk-js/issues/1587. But yes a fully pure vtk.js example to reproduce the issue, it would be the first step for a proper fix.

**Comment by sedghi** [comment] 2021-06-07 13:29
I was able to create a `.vti` format from prostateX data to enable working in a [codeSandbox](https://codesandbox.io/s/prostate-x-ji446?file=/src/index.js)

The process is not well documented, but for those interested: From DICOM files, you need to create a `.vtk` file in 3D slicer and then using this [script](https://github.com/Kitware/vtk-js/blob/master/Utilities/DataGenerator/convert-cli.js) in vtk.js repo you need to run 

`./convert-cli.js -i '/Users/alireza/Documents/prostateX.vtk' -o 'output-data'`

Since recentely I am working a lot on debugging renderings, I create a repo to host images here (https://github.com/sedghi/dicom-test) which you can use. 

The [codeSandbox](https://codesandbox.io/s/prostate-x-ji446?file=/src/index.js) is using the `prsotateX_000.vti` file in my repo. 

I will edit the code to use mprSlice as we are using in react-vtkjs

**Comment by Punzo** [comment] 2022-09-12 12:43
Duplicate (https://github.com/OHIF/Viewers/issues/2847), closing this

**Closed by Punzo** 2022-09-12 12:43 UTC
Labels: Triage :white_flag:, IDC:candidate
