### ISSUE TITLE
Problems with MPR for a SEG series

### ISSUE THREAD

**Issue by fedorov** [OHIF/Viewers#2371] opened 2021-04-20 14:01 UTC
Rendering of the second SEG series in MPR does not work as expected for this study: 1.3.6.1.4.1.14519.5.2.1.7311.5101.170561193612723093192571245493 (this is from IDC v2 data, not yet public).

![image](https://user-images.githubusercontent.com/313942/115408901-41d16700-a1bf-11eb-8a3a-f3cbbaa9a67b.png)

**Comment by fedorov** [comment] 2021-04-20 14:13
Per slack discussion, for now agreed to monitor this issue and not prioritize, since it may be addressed by the upcoming off-screen rendering (@Punzo any comments about the timeline for the public availability of that? is that going to be in v2 or v3)

**Comment by Punzo** [comment] 2021-04-20 14:20
The issue is not related to the segmentation, but to the rendering/crosshair. There are two options:
1) it is a rendering bug in vtk at specific camera settigns/ray sampling etc...
2) the crosshair position is wrongly initialized.

**Comment by Punzo** [comment] 2022-09-12 12:40
Duplicate (https://github.com/OHIF/Viewers/issues/2847), closing

**Closed by Punzo** 2022-09-12 12:40 UTC
Labels: Community: Report :bug:, Awaiting Reproduction, Triage :white_flag:, IDC:candidate
