### ISSUE TITLE
Inclusion of VTK extension causes the OHIF study viewer to crash

### ISSUE THREAD

**Issue by robertsoakes** [OHIF/Viewers#1722] opened 2020-05-11 23:49 UTC
Thank you for creating an amazing set of components.

I've been trying to embed the OHIF viewer into an existing web application for viewing Dicoms pulled from Orthanc, and I'm running into trouble with with the VTK plugin. Is there an minimal working example that I can inspect to see how to include it?

Right now, I'm using a checkout from the recent `master` branch with a custom script include build of the extension that I've adapted from the example in your documentation. Here's what the HTML and viewer initialization look like:

```html
<body>
  ...
  <div id="root"></div>

  <!-- OHIF and Plugins -->
  <script type="text/javascript" src="/js/ohif/sonador.app-config.js" crossorigin></script>
  <script src="/js/ohif/index.umd.js" crossorigin></script>
  <script src="/js/ohif/microscopy/index.umd.js" crossorigin></script>
  <script src="/js/ohif/cornerstone/index.umd.js" crossorigin></script>
  <script src="/js/ohif/segmentation/index.umd.js" crossorigin></script>
  <script src="/js/ohif/vtk/index.umd.js" crossorigin></script>
  ...
  <!-- Initialize Viewer -->
  <script>
    // Application configuration
    var containerId = 'root';

    // Read PACS server connection from JSON string
    window.config.servers.dicomWeb = [
      JSON.parse(document.getElementById('pacs-connection').innerHTML)
    ];

    // Logos and branding for viewer
    window.config.whiteLabeling = {
      createLogoComponentFn: function(React) {
        return React.createElement('a', {
          rel: 'noopener noreferrer',
          className: 'header-brand',
        });
      }
    }

    // Extensions
    window.config.extensions = [OHIFExtDicomMicroscopy, OHIFExtCornerstone, OHIFExtDicomSeg, OHIFExtVtk];

    window.OHIFViewer.installViewer(
      // Configuration and container ID
      window.config, containerId,

      // Completion callback
      function() {
        console.log('OHIF Viewer rendered/updated');  
      }
    );
  </script>
...
</body>
```

The VTK extension loads okay, but when I attempt to load the study viewer, it causes everything to crash with the following error.

![image](https://user-images.githubusercontent.com/3779876/81622735-0e7f3900-93af-11ea-9af9-b1dfc794e56f.png)

This is the relevant information from the link included in the output:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Any thoughts on what might be causing this, or how it might be fixed? I'm happy to repair this and submit a merge/pull request, but need some guidance to get started.

**Comment by dannyrb** [comment] 2020-05-12 00:52
👋 Hello @robertsoakes,
We primarily build and serve the PWA version of the OHIF Viewer, so the UMD packages have not been tested as extensively. I believe the `VTK` package has thrown this error, or a similar error, for some time.

It may be worth checking how/if it bundles React or expects it as a peerDependency. If there is a version mismatch, or if some other packages similarly conflict between `@ohif/viewer` and `@ohif/extension-vtk`.

Some potential solutions:

1. Build and use the PWA output as a workaround (we know that this works)
2. Investigate and fix this issue so you and others can benefit 🎉 
3. Update our CI to build and include the PWA output as a release asset, or published to a versioned branch of this repository
    - Allowing others (and yourself) to leverage the PWA output without having to execute a build

Sorry I'm not much more help. Unfortunately, we have had the bandwidth to dig much more into this one.

**Comment by dannyrb** [comment] 2020-05-12 01:22
Related: https://github.com/OHIF/Viewers/issues/1713#issuecomment-627046358

**Comment by robertsoakes** [comment] 2020-05-12 04:07
@dannyrb Thanks for responding so quickly with the suggestions. I’ll start by comparing the build manifest for VTK against the other plugins, and try and spot for differences. 

The project I’m working on needs three the the volume rendering and three dimensional capabilities of VTK, and we’ve decided to build it on OHIF; so this seems like a good time to dig in.

I’ll see if I can get you a merge request in the next few days. Cheers!

**Comment by salimkanoun** [comment] 2020-05-13 14:55
@robertsoakes 
I pointed this issue some weeks ago : https://github.com/OHIF/Viewers/issues/1003
You might find additional informations in this issue.

Would be very great if you able to fix it,

Best regards,

Salim

**Comment by Dev-Now** [comment] 2020-11-22 08:15
@robertsoakes Any good news on this? 

I have the same issue with the dicom-rt extension

**Comment by salimkanoun** [comment] 2020-11-22 09:47
It's seems the script tag deployment is difficult to maintain,
I now build OHIF from sources, to generate the static build to serve, all extensions are working properly this way

**Comment by robertsoakes** [comment] 2020-11-23 15:07
@Dev-Now Unfortunately, no. We spent time trying to track it down, but couldn't find the set of clashes that appeared to be causing the issue. (The build system for OHIF is much more complicated than anything I've even dealt with, including most of the other members of my team.) We even had a consultant look at it, and he basically said, "I can probably figure this out, but it's going to take a lot of time to come up to speed.

We eventually decided to re-tool, based on recommendation by @dannyrb, "Use the PWA build." That meant two things:

* Only embedding a subset of the viewer functionality (we currently use the core, PDF, HTML, and Microscopy pieces)
* Modifying our backend system so that it's compatible with both an embedded script and the PWA build

**Comment by robertsoakes** [comment] 2020-11-23 15:12
@salimkanoun 

> I now build OHIF from sources to generate the static build to serve, all extensions are working properly this way.

Can you expand on how you are doing this? Are you using the PWA builds or another build mechanism?

**Comment by salimkanoun** [comment] 2020-11-23 15:23
@robertsoakes just have a look at this file https://github.com/salimkanoun/Orthanc-Tools-JS/blob/dev/Dockerfile

this section grab OHIF source got from their git, install dependencies and build it to generate the build that is simply copy and pasted in a statically serve folder of my backend (in this case '/viewer' path)

FROM node:12.16.2 as ohif
RUN apt-get update -qy && \
    apt-get install -y --no-install-recommends apt-utils\
    git
WORKDIR /ohif
RUN git clone -b feat/scroll-sync https://github.com/OHIF/Viewers.git
WORKDIR /ohif/Viewers
RUN yarn install
RUN QUICK_BUILD=true PUBLIC_URL=/viewer/ yarn run build
WORKDIR /ohif/Viewers/platform/viewer/dist

COPY --from=ohif /ohif/Viewers/platform/viewer/dist ./build/viewer

**Comment by Dev-Now** [comment] 2020-11-23 18:30
> 
> 
> @Dev-Now Unfortunately, no. We spent time trying to track it down, but couldn't find the set of clashes that appeared to be causing the issue. (The build system for OHIF is much more complicated than anything I've ever dealt with. Other members of my team have also been unable to find the source of the problem, though we strongly think it's related to incompatible versions of React or one of its dependencies.) We even had a consultant look at it, and he basically said, "I can probably figure this out, but it's going to take a lot of time to come up to speed."
> 
> Because of that, we eventually decided to re-tool. Based @dannyrb recommendation above ("Use the PWA build") we've done two things:
> 
>     * Only embed a subset of the viewer functionality (we currently use the core, PDF, HTML, and Microscopy pieces) in our Django application (see https://code.oak-tree.tech/oak-tree/medical-imaging/sonador)
> 
>     * Modifying our backend system so that it's compatible with both an embedded script and the PWA build (work on this is ongoing)

@robertsoakes Thank you for clarifying this. It is indeed complicated, I had about 4 hours of frustration before giving up and deciding to use the PWA build... Seeing your response, I am glad I did not waste more time on this.
I would have been much more clean for our internal solution to use the UMD extensions as we have customers with different requests... But it is ok for now.

**Comment by dannyrb** [comment] 2020-11-23 18:46
FWIW, using PWA build and code splitting on features specific to clients is a much better experience for end users.

Embedded UMD is _supposed_ to be simpler, and ideal for things like embedding in Google Collab, a Python Notebook, etc.

**Comment by PoyangLiu** [comment] 2020-11-23 20:36
A few months ago when I started tinkering with the OHIF's embedded build, I ran into this problem too.  At the time, it was caused by loading [duplicate React](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) at run-time.  This was caused by incorrectly specified `dependencies` vs `peer-dependencies` as pointed out by @dannyrb and others.  Once I move the offending react-related package  into `peerDependencies`, everything worked out.

Although I did not include `vtk` or `dicom-rs` extension, it was my own extension.

Looking at [vtk/package.json](https://github.com/OHIF/Viewers/blob/master/extensions/vtk/package.json#L53) and [cornerstone/package.json](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/package.json#L54), I don't see any obvious culprit.  The only thing that I see odd is:

[extensions-cornerstone](https://github.com/OHIF/Viewers/blob/master/extensions/cornerstone/package.json#L46)
* peerDependencies: [react-resize-detector ^3.4.0]
* dependencies: ['react-cornerstone-viewport']

[react-cornerstone-viewport](https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/package.json#L40)
* **dependencies**: [react-resize-detector ^4.2.1]

[react-resize-detector](https://github.com/maslianok/react-resize-detector/blob/master/package.json#L16)
* does *NOT* specified `react` in its `dependencies` nor `peer-dependencies`

Perhaps the `react-resize-detector` should be `peer-dependencies` of `react-cornerstone-viewport`?
Just sharing my 2cents.

**Comment by haritharash** [comment] 2021-01-25 11:17
i faced similar issue,, how to fix this? the apps crash when i'm try to build with vtk extension,, any suggestions on how to fix this?

**Comment by Fraktalis** [comment] 2021-04-28 10:55
Hello everyone, 

I'm quite new in using OHIF, and i'm also very interested in using the UMD version of OHIF, to decouple the viewer from the core logic. Of course, I encountered the problem mentioned above. 

I came accross this config parameter of webpack called [externals](https://webpack.js.org/configuration/externals/). 
It seems that even though React & ReactDOM are peer dependencies, they can still embedded in extensions UMD packages, and this option explicitly tells webpack to ignore React during the bundling process. 
adding 
`externals: {
      'react': {
        root: 'React',
        commonjs2: 'react',
        commonjs: 'react',
        amd: 'react'
      },
      'react-dom': {
        root: 'ReactDOM',
        commonjs2: 'react-dom',
        commonjs: 'react-dom',
        amd: 'react-dom'
      }
    },` 
in each `webpack.prod.js` file removes the **React minified error 321**, but triggers a Drag Drop context error when loading a study.  

More generally, I've seen in recent commits such as [54dd738](https://github.com/OHIF/Viewers/commit/54dd738f61816e90dd22236d97b0bea13e2fb03d#diff-eb7d4ba562678976152578177e0f20adadd77de4c5ba97428c92fb1d5dfb6c95R2) a relative import of `core` folder from `dicom-segmentation` extension. I'm not sure such an import could work if everything is UMD-packaged. 

Does that mean that UMD should still be avoided ? And that I should rely on the PWA build instead ?

Thank you in advance for your answer.

**Comment by racacere** [comment] 2021-08-20 21:34
Hi there,

At my company we find a workaround for this problem, it consists in import al needed plugins at `platform/viewer/src/index-umd,js`, in the same way that it is done in `platform/viewer/src/index-umd,js`:

```
import 'regenerator-runtime/runtime';
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.js';

import OHIFVTKExtension from '@nurohif/extension-vtk';
import OHIFDicomHtmlExtension from '@nurohif/extension-dicom-html';
import OHIFDicomSegmentationExtension from '@nurohif/extension-dicom-segmentation';
import OHIFDicomRtExtension from '@nurohif/extension-dicom-rt';
import OHIFDicomMicroscopyExtension from '@nurohif/extension-dicom-microscopy';
import OHIFDicomPDFExtension from '@nurohif/extension-dicom-pdf';
import OHIFDicomTagBrowserExtension from '@nurohif/extension-dicom-tag-browser';
//import OHIFDebuggingExtension from '@nurohif/extension-debugging';

function installViewer(config, containerId = 'root', callback) {
  const container = document.getElementById(containerId);

  const defaultExtensions = [
    OHIFVTKExtension,
    OHIFDicomHtmlExtension,
    OHIFDicomMicroscopyExtension,
    OHIFDicomPDFExtension,
    OHIFDicomSegmentationExtension,
    OHIFDicomRtExtension,
    //OHIFDebuggingExtension,
    OHIFDicomTagBrowserExtension,
  ];

  if (!container) {
    throw new Error(
      `No root element found to install viewer. Please add a <div> with the id '${containerId}', or pass a DOM element into the installViewer function.`
    );
  }

  return ReactDOM.render(
    <App config={config} defaultExtensions={defaultExtensions} />,
    container,
    callback
  );
}

export { App, installViewer };

```

Maybe this is not the best solution for all use cases but it can be useful for someone. You also can be the changes at our public fork of Ohif: https://gitlab.nursoft.cl/foss/ohif-viewer/-/commit/41d2f5095e3cca9ed08bf9962664164a88f43224?view=parallel

Best regards.

**Comment by ranasrule** [comment] 2021-11-05 11:50
> 
> 
> Hi there,
> 
> At my company we find a workaround for this problem, it consists in import all needed plugins at `platform/viewer/src/index-umd,js`, in the same way that it is done in `platform/viewer/src/index.js`:
> 
> ```
> import 'regenerator-runtime/runtime';
> import React from 'react';
> import ReactDOM from 'react-dom';
> import App from './App.js';
> 
> import OHIFVTKExtension from '@nurohif/extension-vtk';
> import OHIFDicomHtmlExtension from '@nurohif/extension-dicom-html';
> import OHIFDicomSegmentationExtension from '@nurohif/extension-dicom-segmentation';
> import OHIFDicomRtExtension from '@nurohif/extension-dicom-rt';
> import OHIFDicomMicroscopyExtension from '@nurohif/extension-dicom-microscopy';
> import OHIFDicomPDFExtension from '@nurohif/extension-dicom-pdf';
> import OHIFDicomTagBrowserExtension from '@nurohif/extension-dicom-tag-browser';
> //import OHIFDebuggingExtension from '@nurohif/extension-debugging';
> 
> function installViewer(config, containerId = 'root', callback) {
>   const container = document.getElementById(containerId);
> 
>   const defaultExtensions = [
>     OHIFVTKExtension,
>     OHIFDicomHtmlExtension,
>     OHIFDicomMicroscopyExtension,
>     OHIFDicomPDFExtension,
>     OHIFDicomSegmentationExtension,
>     OHIFDicomRtExtension,
>     //OHIFDebuggingExtension,
>     OHIFDicomTagBrowserExtension,
>   ];
> 
>   if (!container) {
>     throw new Error(
>       `No root element found to install viewer. Please add a <div> with the id '${containerId}', or pass a DOM element into the installViewer function.`
>     );
>   }
> 
>   return ReactDOM.render(
>     <App config={config} defaultExtensions={defaultExtensions} />,
>     container,
>     callback
>   );
> }
> 
> export { App, installViewer };
> ```
> 
> Maybe this is not the best solution for all use cases but it can be useful for someone. You also can be the changes at our public fork of Ohif: https://gitlab.nursoft.cl/foss/ohif-viewer/-/commit/41d2f5095e3cca9ed08bf9962664164a88f43224?view=parallel
> 
> Best regards.

I'm unable to access your fork of OHIF. Can you please fix the link?

**Comment by racacere** [comment] 2021-11-05 19:44
@ranasrule please try again, yesterday we had some problems with our Gitlab server, now is back online.

**Comment by ssemeria** [comment] 2022-04-01 08:43
Hi all,

sorry to reopen an old thread, I can move my comment elsewhere if it's not appropriate here.
I would like to better understand this issue because we are trying to embed OHIF Viewer in our existing application. We already embedded an older version (1.0.3) of the viewer using the UMD approach.
We are trying to upgrade because we are interested in the 2D MPR functionality. 
I don't fully understand which version of the viewer is considered "stable" (the documentation seems to suggest that the 2.X is still the stable one) but we tried the latest one (4.9.24).
We first tried the UMD approach by including both the UMDs of the viewer and the VTK extension but we got a crash of the viewer due to (as far as I can understand) the multiple inclusion of react and reactDOM by both UMD packages.
We then tried the approach suggested by @racacere  of creating a customized UMD for the viewer embedding the needed extensions, but we then got a crash when starting the service worker (as far as I can understand the service worker scripts are embedded into the UMD an cannot be found).
I then tried to deploy it as a PWA, copying all files inside my own app and then trying to adapt my app code but I got lots of unresolved files probably due to wrong inclusion path somewhere (the service worker seems to include many different files at runtime).
Can someone suggest a good approach for embedding both the viewer and the VTK extension in an existing app?
The version does not matter too much as far as the 2D MPR functionality works...
Thanks a lot

**Comment by sedghi** [comment] 2023-10-12 20:32
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.

**Closed by sedghi** 2023-10-12 20:32 UTC
Labels: Up For Grabs :raising_hand_woman:, Bug: Verified :bug:
