### ISSUE TITLE
Changing rows per page dropdown on Study List should refresh results

### ISSUE THREAD

**Issue by swederik** [OHIF/Viewers#553] opened 2019-06-14 11:32 UTC
Right now if you switch from 25 to 50 in the rows per page selector on the study list, nothing happens. It should perform the query again and display the results.

**Comment by biharck** [comment] 2019-06-14 17:55
After an investigation, I notice that there is no issue on the frontend side. Viewers are passing the right limit number to the backend service such as https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies?limit=50&offset=0&OTHER_PARAMETERS.... but are not getting more than 25 items through the payload.

If it says less than 25 it works, but more than that it doesn't. 

I Talked to @swederik and he'll do the changes on the backend side.

**Comment by dannyrb** [comment] 2019-08-25 03:08
Unable to reproduce. Closing.

**Closed by dannyrb** 2019-08-25 03:08 UTC
Labels: Bug: Verified :bug:
