### ISSUE TITLE
IDC - Check issue with problem RTSTRUCT

### ISSUE THREAD

**Issue by JamesAPetts** [OHIF/Viewers#2063] opened 2020-09-24 13:28 UTC
This struct has an issue on IDC:
1.3.6.1.4.1.14519.5.2.1.1706.4009.166062280490896869511085725416

**Comment by fedorov** [comment] 2020-09-24 13:29
Follow up on the earlier issue: #1958

**Comment by fedorov** [comment] 2020-09-24 13:34
I confirmed that there is only one RTSTRUCT series 1.3.6.1.4.1.14519.5.2.1.1706.4009.176438372608789216964322883598/1.3.6.1.4.1.14519.5.2.1.1706.4009.198949163998597526872719573002.dcm, and it only has POINT and CLOSED_PLANAR for `ContourGeometricType`.

**Comment by JamesAPetts** [comment] 2020-10-05 10:29
So each `ContourSequence` in this case has no `ContourImageSequence`, which is fine and standards compliant as it is type 3.
The question is what do we do in this case?

We have the 3D positions and the frame of reference, so the RTSTRUCT is well defined in 3D space.
The issue is with cornerstone, which we are currently using to render these contours is a 2D library.

We could try and map each contour to the nearest slice, but you would have to:
- Make the initial assumption that the contours are in plane.
- Find the nearest slice in the acquisition direction to the first point of the contour.
- Check if all points in the contour are in plane within some threshold (Isn't skewed to have a portion of its data past the next slice, or completely out of plane).
- Select this frame to map to if its in-plane.
- Throw an error in a popup that out of plane contours are not supported?

What do you think @fedorov ?


Obviously we wouldn't have this issue if we were just using `vtkjs`, but we don't have support for such rich annotations in that framework yet, unfortunately.

**Comment by fedorov** [comment] 2020-10-05 15:25
I started to investigate how often this is missing in our data, and hit a bump where an instance that has a sequence non-empty results in an empty corresponding column in the BQ table. I reported this, will wait to hear back until spending time with BQ.

To respond to your question, the approach you suggest sounds good to me. Is there a vision how this situation would be handled in the next version of OHIF? Would working on this now be useful for that next version?

**Comment by pieper** [comment] 2020-10-05 17:02
We had defined the MVP as only handling RTSTRUCT on 2D, but now that we are quasi-post-MVP maybe we should define a next milestone and hash out what is in and out of scope for it based on resources available.  Display of these 3D RTSTRUCTs in MPR view only could be a feasible solution (or converting them to 2D via vtk)

**Comment by fedorov** [comment] 2020-10-05 17:20
@pieper so you define an RTSTRUCT as 3D if it does not have the optional reference to the SOPInstanceUID defining the slice plane? 

I don't think it is 3D if that reference is missing, and actually it might be 3D if that reference is present, so there is a need for assumptions and some checks no matter what.

I agree we need to define the post-MVP scope.

**Comment by pieper** [comment] 2020-10-05 17:27
I don't really know anything about the data in question, but as a general topic display of RTSTRUCT in 3D makes a lot of sense so it should be supported in the vtk-based MPR view.  I'm not sure how much we want to map it back to cornerstone if the slice plane reference isn't provided.

Now that we have the BQ for all the IDC data we could revisit the topic of assessing what data types exist and whether we are able to display the correctly.  This could help prioritize development in our next phase.

**Comment by fedorov** [comment] 2020-10-05 18:49
Yes, I agree we should discuss that general topic, but we should also decide what to do with this specific problematic RTSTRUCT we currently have in IDC.

**Comment by fedorov** [comment] 2020-10-05 18:55
Also, this response I've just received back from google throws a wrench of an unknown size into our ability to relying on BQ for DICOM metadata ... :-\

![image](https://user-images.githubusercontent.com/313942/95119939-c3c5db00-071a-11eb-9bf5-96f6d16148c9.png)

**Comment by JamesAPetts** [comment] 2020-10-06 09:05
> Also, this response I've just received back from google throws a wrench of an unknown size into our ability to relying on BQ for DICOM metadata ... :-\

Oh yeah, that's nasty.

The difficulty is react-vtkjs-viewport doesn't have any good annotation framework yet, the closest we have is the crosshairs. It may be pretty slow to do something with SVG, so this'd likely have to be done on the GPU.

Shall we talk about it on Thursday?

**Comment by fedorov** [comment] 2020-10-13 14:17
@pieper can we get this into the sandbox? This one is probably one of the most critical issues for IDC MVP, since most of the (very few) RTSTRUCT datasets we currently have there are broken because of this issue.

**Comment by pieper** [comment] 2020-10-13 16:31
@JamesAPetts will you be preparing a PR for the IDC-OHIF fork with all the recent changes?  Last time there were all those merge conflicts so if it's going to be that way again would be great if you could handle it.  Let me know if we should talk through the workflow.  I was hoping the IDC customizations could be rebased against the upstream.

**Comment by fedorov** [comment] 2020-10-14 13:35
@pieper do we need to wait for James to get it into the sandbox as well? Does sandbox use fork or master?

**Comment by fedorov** [comment] 2020-10-14 15:22
Reopening until we can confirm this works either in the sandbox, or in the IDC portal. I don't want to lose track of this.

**Comment by pieper** [comment] 2020-10-14 16:59
Sounds good.  Per slack conversation James says he'll rebase and make PR tomorrow.

**Comment by fedorov** [comment] 2020-10-14 17:14
Sure. So the sandbox is using fork, not main repo, right?

**Comment by pieper** [comment] 2020-10-14 17:39
Yes, sandbox is using the fork so we can test the integration of ohif changes and our changes before making the tag for Bill.

You can test the current ohif master at viewer.ohif.org.  You could put test datasets on server.dcmjs.org if you want.

**Comment by fedorov** [comment] 2020-10-14 17:40
Thanks. I will test tomorrow.

**Comment by fedorov** [comment] 2020-10-15 15:07
@JamesAPetts let me close this issue once I confirm it is working in IDC test or sandbox. I will assign to myself to make sure this is clear.

**Comment by JamesAPetts** [comment] 2020-10-15 15:18
Gotcha.

**Comment by fedorov** [comment] 2020-10-18 03:29
Works!

**Closed by fedorov** 2020-10-18 03:29 UTC
Labels: IDC:priority
