### ISSUE TITLE
cornerstoneExtensionConfig not working in prod

### ISSUE THREAD

**Issue by tillmon** [OHIF/Viewers#1332] opened 2019-12-26 08:46 UTC
The following setting in [default.js](https://github.com/OHIF/Viewers/blob/master/platform/viewer/public/config/default.js) is working in dev, but not in prod.

```json
cornerstoneExtensionConfig: {
    tools: {
      Zoom: {
        configuration: {
          minScale: 0.05,
          maxScale: 2.0,
        },
      },
    },
  },
´´´

**Comment by dannyrb** [comment] 2019-12-26 13:59
@tillmon can you provide a reproduction with a prod build using CodeSandbox?

**Comment by tillmon** [comment] 2019-12-26 14:34
Sure, I hope this is right:

https://codesandbox.io/s/viewer-script-tag-6pbyt

**Comment by tillmon** [comment] 2019-12-27 01:09
I tracked the bug down to this line:

https://github.com/OHIF/Viewers/blob/2e215aed4cc283794a4365af15d3203068676e2c/extensions/cornerstone/src/init.js#L155

tool.name is not accessible in prod.

**Comment by dannyrb** [comment] 2019-12-27 02:00
It looks like your codepen is using an old version of `@ohif/viewer`. When I change this import:

```html
<script src="https://unpkg.com/@ohif/viewer@1.0.3/dist/index.umd.js" crossorigin></script>
```

To the latest version:

```html
<script src="https://unpkg.com/@ohif/viewer@3.3.3/dist/index.umd.js" crossorigin></script>
```

The configuration works as expected.

**Comment by tillmon** [comment] 2019-12-27 11:31
Yes this works. Originally I was using the stand-alone Viewer.

**Comment by dannyrb** [comment] 2019-12-28 21:37
@tillmon, does this resolve your issue, or are you still experiencing it but with a slightly different setup?

**Comment by hackalot** [comment] 2021-07-13 16:45
> I tracked the bug down to this line:
> 
> https://github.com/OHIF/Viewers/blob/2e215aed4cc283794a4365af15d3203068676e2c/extensions/cornerstone/src/init.js#L155
> 
> tool.name is not accessible in prod.

same problem

**Comment by davilima0810** [comment] 2022-09-29 18:50
https://github.com/OHIF/Viewers/blob/2e215aed4cc283794a4365af15d3203068676e2c/extensions/cornerstone/src/init.js#L154

#### just add the tool before this "tools.forEach" like this:

```js
csTools.addTool(csTools.ZoomTool, {
    configuration: {
      invert: false,
      preventZoomOutsideImage: false,
      minScale: 0.05,
      maxScale: 2.0,
    },
  });
```

**Comment by sedghi** [comment] 2023-10-13 16:59
Thank you for your past contributions and for raising this issue related to legacy versions of our OHIF Viewer. Your time and effort have been invaluable in helping us improve the product.

We wanted to update you that our development focus has shifted to OHIF Viewer v3, which is now available for testing on `viewer-dev.ohif.org`. This site is deployed from our `master` branch and incorporates new features, optimizations, and bug fixes. If you're still using `viewer.ohif.org`, it's worth noting that this is deployed from our `release` branch and may not have the latest updates. You can read more about our branching strategies [here](https://docs.ohif.org/development/getting-started#developing).

Given the move to Version 3, we are closing older issues that pertain to Versions 1 and 2, as we are no longer providing support for those versions. If you find that the issue you've raised is still relevant in Version 3, we encourage you to reopen this issue or create a new one for proper triage.

Thank you for your understanding and continued support.

**Closed by sedghi** 2023-10-13 16:59 UTC
