### ISSUE TITLE
MPR rendering "black line"

### ISSUE THREAD

**Issue by salimkanoun** [OHIF/Viewers#1083] opened 2019-10-24 11:05 UTC
Hi there,

I noticed a but with the MPR mode.
In the MPR there is a single voxel line that apear in each view, it maybe be partial or full lenght.

See in the attached capture, taken from the OHIF demo server, I took the capture during volume loading and it is more visible (see the vertical line in the middle image). This line stays visible after full volume loaded.

Best regards,

Salim
![OHIF Line Bug](https://user-images.githubusercontent.com/25229822/67479725-f9cf9380-f65e-11e9-80a5-bcd81178645d.png)

**Comment by swederik** [comment] 2019-10-24 15:06
We've seen this one as well and don't have a good answer for it yet. It seems intermittent and maybe depends on browser zoom scale and the exact rotation of the volume.

**Comment by salimkanoun** [comment] 2019-10-29 16:41
Souds like the bug is gone in the last version isn't it ? 

By the way, is there any plan to add Zoom / Pan to this MPR view ? 

Salim

**Comment by dannyrb** [comment] 2019-10-29 17:10
Oh. That's interesting. I don't see it anymore either. Likely a side effect of one of @JamesAPetts recent changes?

**Comment by JamesAPetts** [comment] 2019-10-29 17:18
No idea, since we didn't know what caused it in the first place. Maybe the issue isn't present in the new parallel projection routes the shader takes 🤔 . Lets see if it pops up again. Did you have an easy way to reproduce the problem which is now fixed previously @dannyrb ?

**Comment by JamesAPetts** [comment] 2019-10-30 11:19
I'll close this for now. It may be present when we get to volume rendering as we'll be using the perspective camera again for that, we'll see. 👍

**Closed by JamesAPetts** 2019-10-30 11:19 UTC
Labels: Bug: Verified :bug:
