### ISSUE TITLE
windows build does not work with 

### ISSUE THREAD

**Issue by gzt036** [OHIF/Viewers#1950] opened 2020-08-04 00:26 UTC
windows build won't work with line 37 and 38 in package.json

  "lerna:cache": "[ $NETLIFY_RESTORE = 1 ] && ./netlify-lerna-cache.sh || :"

after removing '[ $NETLIFY_RESTORE = 1 ] ' yarn install could finish.

Also, sourcemap does not seem to work with OHIF viewer. Any tip how to make it working? Please help, thanks!

**Comment by PoyangLiu** [comment] 2020-08-04 01:00
This seems to be a duplicate of #1926.

Re source-map.  Are you using `npm run dev'?  See [webpack.base.js](https://github.com/onepackius/Viewers/blob/OnePacs/master/.webpack/webpack.base.js#L32).  The full source map takes a long time to build and is only used in `production`.  You can change line 32 to use `source-map` in dev mode as well. Then you should be able to see functional source map.

**Comment by dannyrb** [comment] 2020-08-12 01:15
Short-term, you can remove the npm scripts that include those commands. This is a duplicate of #1926, so I'll close it.

**Closed by dannyrb** 2020-08-12 01:15 UTC
