### ISSUE TITLE
RightSidePanel: Cannot read property 'SeriesInstanceUID' of undefined error returned

### ISSUE THREAD

**Issue by madelyngreyes** [OHIF/Viewers#2123] opened 2020-10-19 17:35 UTC
### Describe the Bug

While working with RTSTRUCT and the OHIF viewer you are returned the error message, "RightSidePanel: Cannot read property 'SeriesInstanceUID' of undefined"

### What steps can we follow to reproduce the bug?

1. Open the study 1.3.6.1.4.1.14519.5.2.1.1706.4009.166062280490896869511085725416
2. Open the RTSTRUCT tab on the right
3. Select the second series and drag into the canvas 
4. You are returned the error message, "RightSidePanel: Cannot read property 'SeriesInstanceUID' of undefined"

![2020-10-19 (9)](https://user-images.githubusercontent.com/16824894/96490553-fab5e980-120e-11eb-959a-04b25c31ed9e.png)

```
============= SESSION INFO =============
== App ==
version	4.5.21
== Extensions Versions ==
generic-viewer-commands	4.5.21
cornerstone	2.9.6
vtk	1.7.13
html	1.2.9
microscopy	0.51.3
pdf	1.0.6
com.ohif.dicom-segmentation	0.4.7
rt	0.4.9
dicom-p10-downloader	0.1.6
dicom-tag-browser	undefined
== Browser Info ==
name	 chrome
os	 Windows 10
type	 browser
version	 86.0.4240
== URL ==
URL	 1.3.6.1.4.1.14519.5.2.1.1706.4009.166062280490896869511085725416
== Viewport Layout ==
Rows	1
Columns	1
== Viewports ==
[0,0]	1.3.6.1.4.1.14519.5.2.1.1706.4009.235001741732391381168268744865
```

**Comment by fedorov** [comment] 2020-11-05 14:39
This is probably related to #2117

**Comment by igoroctaviano** [comment] 2020-11-13 17:13
@madelyngreyes @fedorov fixed here: #2168.
This study contains only CT (which has RTStructs in it) and RTDOSE modalities. Currently we check only for RTSTRUCT in the RT extension, thats why things were broking. Now the panel button will only show for non-empty RTStructs.

**Comment by fedorov** [comment] 2020-11-13 17:50
> This study contains only CT (which has RTStructs in it) 

Can you clarify what you mean by the above, that CT contains RTStructs?

**Comment by igoroctaviano** [comment] 2020-11-13 18:16
> > This study contains only CT (which has RTStructs in it)
> 
> Can you clarify what you mean by the above, that CT contains RTStructs?

Yes. The thing is, during debugging i realised that this study didn't had any series with RTSTRUCT modality although the RTStructs were being loaded correctly in the viewport. I fixed the RT struct panel now so it will be disabled for other modalities properly.

**Comment by igoroctaviano** [comment] 2020-11-16 18:49
Update: The problem was caused by a reactivity bug with the panel and the active viewport, the loading should only appear for rtstructs and be empty otherwise. I have updated the PR so now the panel will behave correctly.

**Comment by fedorov** [comment] 2020-12-09 14:51
@madelyngreyes can you please confirm if this is fixed in the testing tier?

**Comment by madelyngreyes** [comment] 2020-12-09 20:41
![OHIF viewer error](https://user-images.githubusercontent.com/16824894/101684683-cc959e80-3a34-11eb-8fc0-e486fa93e840.PNG)

I seem to be returning a different error with the ToolBarRow this time.

**Comment by fedorov** [comment] 2020-12-09 21:17
@madelyngreyes so it is the same as in https://github.com/OHIF/Viewers/issues/2117#issuecomment-741823904

**Comment by madelyngreyes** [comment] 2020-12-14 13:16
Currently PR51 is live in the dev tier, running the steps from the original bug you are no longer returned an error message but, a blank RT Structure sets panel. Study used is, "1.3.6.1.4.1.14519.5.2.1.1706.4009.166062280490896869511085725416" 

![RT struct appears as a blank panel](https://user-images.githubusercontent.com/16824894/102085223-556d5b00-3de4-11eb-8fb9-0dfa04d06f79.PNG)

Text could be added, "No data available" to make it clear to the end user.

**Comment by fedorov** [comment] 2020-12-14 14:51
I think when RTSTRUCT does not apply to the specific image series, the button and the panel should not be shown.

**Comment by igoroctaviano** [comment] 2021-01-19 12:59
> I think when RTSTRUCT does not apply to the specific image series, the button and the panel should not be shown.

@fedorov I think we missed this one during the last call, this one should be prioritized as well?

**Comment by fedorov** [comment] 2021-01-19 14:58
> this one should be prioritized as well?

Yes!

**Closed** 2022-09-12 12:36 UTC
Labels: Community: Report :bug:, Awaiting Reproduction, Triage :white_flag:, IDC:priority
